export const ROOT_EDITOR_CLASS = 'dnd-root-editor';
export const MAIN_EDITOR_CONTENT_CLASS = 'dnd-main-content';
export const EMBED_BLOCK_SELECTOR = '.cm-embed-block, .cm-callout, .cm-preview-code-block, .cm-math, .MathJax_Display';
export const DROP_INDICATOR_SELECTOR = '.dnd-drop-indicator';
export const DROP_HIGHLIGHT_SELECTOR = '.dnd-drop-highlight';

export const DRAG_HANDLE_CLASS = 'dnd-drag-handle';
export const LINE_HANDLE_CLASS = 'dnd-line-handle';
export const EMBED_HANDLE_CLASS = 'dnd-embed-handle';
export const DROP_INDICATOR_CLASS = 'dnd-drop-indicator';
export const DROP_HIGHLIGHT_CLASS = 'dnd-drop-highlight';
export const DRAG_GHOST_CLASS = 'dnd-drag-ghost';
export const DRAGGING_BODY_CLASS = 'dnd-dragging';
export const DRAG_SOURCE_LINE_NUMBER_CLASS = 'dnd-drag-source-line-number';
export const DRAG_SOURCE_LINE_CLASS = 'dnd-drag-source-line';
export const RANGE_SELECTED_LINE_CLASS = 'dnd-range-selected-line';
export const RANGE_SELECTED_HANDLE_CLASS = 'dnd-range-selected-handle';
export const RANGE_SELECTION_LINK_CLASS = 'dnd-range-selection-link';
export const MOBILE_GESTURE_LOCK_CLASS = 'dnd-mobile-gesture-lock';
